name: PHP Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: cd backend && composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: backend/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: cd backend && composer install --prefer-dist --no-progress

    # Set up environment variables needed for tests
    - name: Set up environment
      run: echo "JWT_SECRET=github_actions_test_secret" >> $GITHUB_ENV
      
    - name: Run test suite
      run: cd backend && composer test
